[package]
name = "ubuntu-contents"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.79"
regex = "1.11.1"
flate2 = { version = "1.1.1", default-features = false, features = ["zlib-ng"] }
ureq = { version = "3.0.10", default-features = false }
serde_json = "1.0.140"
